workspace: Calculator-TCA.xcworkspace
retain_assign_only_properties: true
retain_unused_protocol_func_params: true
retain_objc_accessible: true
retain_public: true
external_encodable_protocols: true
schemes:
- Calculator-TCA
targets:
- Calculator-TCA
verbose: false
skip_build: false
strict: false
format: xcode
