# list of rules will be available at:
# https://realm.github.io/SwiftLint/rule-directory.html

#disable following rules
disabled_rules:
    - multiple_closures_with_trailing_closure
    - trailing_closure
    - closure_body_length
    - empty_xctest_method

# opt-in following rules
opt_in_rules: 
  - anyobject_protocol
  - capture_variable
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_self
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - raw_value_for_camel_cased_codable_enum 
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition


# paths to include
included:


# paths to ignore during linting
excluded:
  - ./*/External/
  - ./*/Generated/
  - ./*/Preview Content/
  - ./Pods/

custom_rules:
  disable_print:
    included: ".*.swift"
    name: "Print usage"
    regex: "print"
    message: "Prefet debugPrint"
    severity: error

# custom values
cyclomatic_complexity:
  ignores_case_statements: true

file_length:
  warning: 1000
  error: 1200

force_cast: warning
force_try: warning

function_body_length:
  warning: 50
  error: 70

identifier_name:
  min_length: 
    error: 0
    warning: 0

line_length: 
  warning: 200
  error: 220

trailing_whitespace:
  ignores_empty_lines: true

type_body_length:
  warning: 250
  error: 400

vertical_whitespace:
  max_empty_lines: 2
