name: Cache dependencies

on:
  push:
    branches:
      - feature/ci-cd

jobs:
  caching:
    name: Run caching
    runs-on: macos-latest

    steps:
    - name: Cache pods
      uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-pods-

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0

    - name: Install Fastlane
      run: |
        bundle install

    - name: Install Cocoapods
      run: |
        sudo gem install cocoapods
        bundle exec pod install

    - name: Run tests
      run: |
        fastlane unitTests_lane

    - name: Run linting
      run: |
        fastlane lint_lane
