
name: iOS Unit Tests

on:
  push:
    branches:
      - feature/ci-cd

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
    - name: Execute Unit Tests via Fastlane
      run: |
        fastlane unitTests_lane
