name: Unit Tests

# Defines when the action will run.
on:
  push:
    branches:
      - feature/ci-cd

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
     - uses: actions/checkout@v1
     - name: Install Swift
        uses: fwal/setup-swift@v1
        with:
          version: `5.9`
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          destination: "platform=iOS Simulator,name=iPhone SE (3rd generation)"
          env: "platform=iOS Simulator,name=iPhone SE (3rd generation)"
    
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0

    - name: Install Fastlane
      run: |
        bundle install

    - name: Execute Unit Tests via Fastlane
      run: |
        fastlane unitTests_lane
